#conifg.yaml
project:
  name: coffee-mlops
  experiment_name: coffee-quality-exp

paths:
  artifact_dir: artifacts
  artifacts_sub: raw
  log_dir: logs
  database_path: data/coffee.db

data:
  csv_path : "data/coffee_data.csv"
  table_name: coffee_data
  target_column: quality
  trained_file_path: artifacts/trained.csv
  test_file_path: artifacts/test.csv


model:

  random_state: 42

mlflow:
  tracking_uri: mlruns
  experiment_id: 1