#conifg.yaml
project:
  name: coffee-mlops
  experiment_name: coffee-quality-exp

paths:
  artifact_dir: artifacts
  artifacts_sub: raw
  log_dir: logs
  database_path: data/coffee.db

data:
  csv_path : "data/coffee_data.csv"
  table_name: coffee_data
  target_column: quality
  trained_file_path: artifacts/trained.csv
  test_file_path: artifacts/test.csv


model:
  pkl_file_name: preprocessor.pkl
  model_file_name: model.pkl
  random_state: 42

mlflow:
  tracking_uri: mlruns
  experiment_id: 1
  
columns:
  - acidity
  - aroma
  - body
  - flavor
  - aftertaste
  - balance
  - quality

target_column: quality

feature_columns:
  - acidity
  - aroma
  - body
  - flavor
  - aftertaste
  - balance

numerical_columns:
  - acidity
  - aroma
  - body
  - flavor
  - aftertaste
  - balance
  - quality

expected_columns: 7
minimum_nulls: 5

data_types:
  acidity: float64
  aroma: float64
  body: float64
  flavor: float64
  aftertaste: float64
  balance: float64
  quality: float64
